name: Trigger Release Workflow in Repository A

on:
  push:
    tags:
      - '*'

jobs:
  trigger_release_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch Release Workflow in Repository A
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_A_ACCESS_TOKEN }}
          repository: Abikjose/A
          event-type: create_release
